# Generated by Django 6.0.1 on 2026-01-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='text',
            new_name='description',
        ),
    ]
